
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

import resolvedor
from pathlib import Path
alg= resolvedor.SA()
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1536x864")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 864,
    width = 1536,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    1536.0,
    864.0,
    fill="#2A9AD9",
    outline="")

canvas.create_rectangle(
    456.0,
    158.0,
    1079.0,
    259.0,
    fill="#FFFFFF",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=alg.arm.openFile,
    relief="flat"
)
button_1.place(
    x=558.802490234375,
    y=402.3421630859375,
    width=435.197509765625,
    height=108.6578369140625
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=alg.sa,
    relief="flat"
)
button_2.place(
    x=558.802490234375,
    y=530.4727783203125,
    width=435.197509765625,
    height=106.5272216796875
)

canvas.create_text(
    515.0,
    166.0,
    anchor="nw",
    text="Product Allocation",
    fill="#0D54B2",
    font=("IstokWeb Regular", 60 * -1)
)

canvas.create_text(
    292.0,
    780.0,
    anchor="nw",
    text="By: Gabriel Percival Stoppa & Thiago Alves de Queiroz",
    fill="#FFFFFF",
    font=("IstokWeb Regular", 40 * -1)
)

canvas.create_rectangle(
    43.0,
    724.0,
    216.0,
    835.0,
    fill="#FFFFFF",
    outline="")
window.resizable(False, False)
window.mainloop()
